export { default as Navbar } from './Navbar/Navbar';
export { default as About } from './About/About';
export { default as Skills } from './Skills/Skills';
export { default as Experiance } from './Experience/Experience';
export { default as Projects } from './Projects/Projects';
export { default as ProjectDetails } from './Projects/ProjectDetails';
export { default as Education } from './Education/Education';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';